---

- name: Setup/pull the Git repo
  git: repo={{ git_repo }} dest={{ git_root }} update=yes accept_hostkey=yes force=yes
  when: setup_git_repo
  tags:
    - git
    - deploy

- name: Reset perms back to application user
  file: path={{ virtualenv_path }}
        recurse=yes
        owner={{ application_user }}
        group={{ application_group }}
        state=directory
  notify: Restart application
  tags:
    - deploy
