# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-19 15:12
from __future__ import unicode_literals

import core_types.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Approved for publishing?')),
                ('title_fa', models.CharField(max_length=256)),
                ('title_en', models.CharField(max_length=256)),
                ('excerpt_fa', models.TextField()),
                ('excerpt_en', models.TextField()),
                ('link', models.CharField(max_length=1024)),
                ('photo', models.ImageField(upload_to='news_pics')),
                ('featured', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
