# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurednews',
            old_name='excerpt_en',
            new_name='excerpt',
        ),
        migrations.RenameField(
            model_name='featurednews',
            old_name='title_en',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='featurednews',
            name='excerpt_fa',
        ),
        migrations.RemoveField(
            model_name='featurednews',
            name='title_fa',
        ),
        migrations.AddField(
            model_name='featurednews',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Farsi')], default='fa', max_length=3),
            preserve_default=False,
        ),
    ]
