---

- name: Create the application user
  when: set_up_application_user
  user: name={{ application_user }} state=present shell="/bin/bash"

- name: Create the application group
  group: name={{ application_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ application_user }} group={{ application_group }} state=present
