# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-27 15:05
from __future__ import unicode_literals

import core_types.fields
import core_types.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judges', '0010_auto_20190927_1505'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prisons', '0019_auto_20190927_1505'),
        ('core_types', '0001_initial'),
        ('prisoners', '0027_auto_20190924_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanRightViolated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Approved for publishing?')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name')),
                ('name_fa', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name')),
                ('created_by', models.ForeignKey(blank=True, default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Human Right Violated',
                'verbose_name_plural': 'Human Right Violated',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Approved for publishing?')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='report_pics', verbose_name='Report Picture')),
                ('abstract_text', models.TextField(blank=True, null=True)),
                ('abstract_text_en', models.TextField(blank=True, null=True)),
                ('abstract_text_fa', models.TextField(blank=True, null=True)),
                ('victim_count', models.IntegerField(blank=True, null=True, verbose_name='Number of victims in the report')),
                ('partial_date', core_types.fields.PartialDateField(blank=True, null=True)),
                ('explanation_en', models.TextField(blank=True, null=True, verbose_name='Any extra explanation needed to be added to this prisoner')),
                ('explanation_fa', models.TextField(blank=True, null=True, verbose_name='Any extra explanation needed to be added to this prisoner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportChargedWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Approved for publishing?')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name')),
                ('created_by', models.ForeignKey(blank=True, default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Charged With',
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('comment', models.TextField(verbose_name='Comment Text')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='report.Report')),
                ('user', models.ForeignKey(default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
                'verbose_name': 'Conflicts And Considerations',
                'verbose_name_plural': 'Conflicts And Considerations',
            },
        ),
        migrations.CreateModel(
            name='ReportDetention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Approved for publishing?')),
                ('detention_type', models.CharField(blank=True, choices=[('detained_before_sentencing', 'Detained before Sentencing'), ('sentenced', 'Sentenced'), ('transferred', 'Transferred')], max_length=255, null=True, verbose_name='Detention Type')),
                ('detention_year', models.IntegerField(blank=True, null=True, verbose_name='Detention Year (Gregorian)')),
                ('detention_month', models.IntegerField(blank=True, null=True, verbose_name='Detention Month (Gregorian)')),
                ('detention_day', models.IntegerField(blank=True, null=True, verbose_name='Detention Day (Gregorian)')),
                ('detention_year_fa', models.IntegerField(blank=True, null=True, verbose_name='Detention Year (Persian)')),
                ('detention_month_fa', models.IntegerField(blank=True, null=True, verbose_name='Detention Month (Persian)')),
                ('detention_day_fa', models.IntegerField(blank=True, null=True, verbose_name='Detention Day (Persian)')),
                ('detention_is_approx', models.BooleanField(default=False, verbose_name='Detention date is approximate?')),
                ('created_by', models.ForeignKey(blank=True, default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('prison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_detentions', to='prisons.Prison', verbose_name='Prison')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detentions', to='report.Report')),
                ('treatment', models.ManyToManyField(blank=True, to='prisoners.PrisonTreatment', verbose_name='Treatment in prison')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': 'Detention',
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=255, verbose_name='File Name')),
                ('name_fa', models.CharField(max_length=255, null=True, verbose_name='File Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='File Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file', models.FileField(upload_to=b'file_evidence', verbose_name='Data')),
                ('file_thumb', models.ImageField(blank=True, null=True, upload_to=b'file_evidence_thumbnails', verbose_name='Thumbnail')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Approved for publishing?')),
                ('file_type', models.CharField(choices=[('visual_records', 'Visual records'), ('mistreatments', 'Mistreatments'), ('testimonials', 'Testimonials'), ('campaigns', 'Campaigns')], max_length=16)),
                ('created_by', models.ForeignKey(blank=True, default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='report.Report')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'File Evidence',
                'verbose_name_plural': 'File Evidence',
            },
        ),
        migrations.CreateModel(
            name='ReportQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('quote', models.CharField(max_length=255, verbose_name='Quote')),
                ('quote_fa', models.CharField(max_length=255, null=True, verbose_name='Quote')),
                ('quote_en', models.CharField(max_length=255, null=True, verbose_name='Quote')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Approved for publishing?')),
                ('created_by', models.ForeignKey(blank=True, default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('prison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='report.Report')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Quote Evidence',
                'verbose_name_plural': 'Quote Evidence',
            },
        ),
        migrations.CreateModel(
            name='ReportSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Approved for publishing?')),
                ('execution', models.BooleanField(default=False)),
                ('flogging', models.BooleanField(default=False)),
                ('amputation', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_sentences', to='judges.Judge')),
                ('judge_court_and_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_sentences', to='judges.CourtAndBranch')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='report.Report')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Report Sentence',
                'verbose_name_plural': 'Report Sentences',
            },
        ),
        migrations.CreateModel(
            name='ReportSentenceBehaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Approved for publishing?')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_fa', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('judge_behaviour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentence_behaviours', to='judges.BehaviourType')),
                ('report_sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentence_behaviours', to='report.ReportSentence')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Approved for publishing?')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_fields', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='report.Report')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='report',
            name='charged_with',
            field=models.ManyToManyField(blank=True, to='report.ReportChargedWith', verbose_name='Charged with'),
        ),
        migrations.AddField(
            model_name='report',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_types.City', verbose_name='City of arrest'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='report',
            name='domestic_law_violated',
            field=models.ManyToManyField(blank=True, to='prisoners.DomesticLawViolated', verbose_name='Domestic Law Violated'),
        ),
        migrations.AddField(
            model_name='report',
            name='human_right_violated',
            field=models.ManyToManyField(blank=True, to='report.HumanRightViolated', verbose_name='Human Rights violated'),
        ),
        migrations.AddField(
            model_name='report',
            name='international_law_violated',
            field=models.ManyToManyField(blank=True, to='prisoners.InternationalLawViolated', verbose_name='International law violated'),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
    ]
