# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-01 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0010_auto_20190927_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgetimeline',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='judgetimeline',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='judgetimeline',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
