---

- name: Provision {{ application_name }} with Ansible
  hosts: local
  gather_facts: no
  become: true
  remote_user: vagrant

  vars:
    - deploy_env: vagrant
    - application_name: united
    # base
    - application_user: vagrant
    - application_group: vagrant
    - update_apt_cache: yes
    - set_up_application_user: yes
    #Web
    - virtualenv_path: '/home/vagrant/{{ application_name }}'
    - git_root: '/vagrant'
    - django_dir: '/vagrant/app' #  Location of manage.py
    - application_log_dir: '{{ virtualenv_path }}/logs'
    #(Web) Django
    - django_settings_file: '{{ application_name }}.settings.local'
    - django_secret_key: 'iufhqlgqligjweqlfiqjwfloiqwjfwqlefoihfqwfliuhwqflx'
    - run_django_migrate: yes
    - run_django_collectstatic: yes
    - js_directory: '/vagrant'
    - web_enable_ssl: false

  vars_files:
    - vars/db.yml
    - vars/web.yml
    - vault/secrets.yml

  roles:
    - base
    - db
    - vagrant
    - nodejs
    - unitedcron
