# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgetimeline',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='judgetimeline',
            name='description_en',
            field=models.TextField(max_length=1024, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='judgetimeline',
            name='description_fa',
            field=models.TextField(max_length=1024, null=True, verbose_name='Description'),
        ),
    ]
