# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 18:15
from __future__ import unicode_literals

import core_types.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeBehaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Approved for publishing?')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name')),
                ('created_by', models.ForeignKey(blank=True, default=core_types.utils.get_request_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Judge Behaviour',
                'verbose_name_plural': 'Judge Behaviours',
            },
        ),
    ]
