# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0002_judgebehaviour'),
        ('judges', '0002_timeline_increase_description_length'),
    ]

    operations = [
    ]
