# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-07 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0004_auto_20190716_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='mistreatments_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
