# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-09 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0005_judge_mistreatments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='explanation_aea_en',
            field=models.TextField(blank=True, null=True, verbose_name='Any extra explanation needed to be added to this prisoner'),
        ),
        migrations.AddField(
            model_name='judge',
            name='explanation_aea_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Any extra explanation needed to be added to this prisoner'),
        ),
    ]
