# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-12 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0006_auto_20190809_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='aea_mistreatments_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
