# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0007_judge_aea_mistreatments_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgebehaviour',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='judgebehaviour',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='judge',
            name='is_judge',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='JudgeBehaviour',
        ),
    ]
