# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-11 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20190903_1701'),
        ('public', '0002_auto_20190911_1800'),
    ]

    operations = [
    ]
