# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-30 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFrontState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_invalidate_during_next_cron_tick', models.BooleanField(default=False)),
            ],
        ),
    ]
