# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-16 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_write_csv', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
