# for password, ie python -c "from passlib.hash import sha512_crypt; print sha512_crypt.encrypt('your-password')"
---

application_log_dir: "{{ virtualenv_path }}/logs"
requirements_file: "{{ git_root }}/requirements.txt"

# Gunicorn
gunicorn_user: "{{ application_user }}"
gunicorn_group: "{{ application_group }}"
gunicorn_num_workers: 1
gunicorn_max_requests: 0

# Django
django_dir: "{{ git_root }}" #  Location of manage.py
# django_secret_key lives in vault/secrets.yml
run_django_migrate: yes
run_django_collectstatic: yes

# Git
setup_git_repo: yes
git_repo: git@github.com:smallmedia/united.git

# Nginx
nginx_server_name: localhost
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx/nginx_error.log"
nginx_static_dir: "{{ git_root }}/static/"
nginx_media_dir: "{{ git_root }}/media/"

# Nodejs
js_directory: '{{ git_root }}'
