# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import core_types.utils
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0001_initial'),
        ('prisons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPersecutedFor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('name', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_fa', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_en', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'Persecuted Activity',
                'verbose_name_plural': 'Persecuted Activities',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CaseId',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('name', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_fa', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_en', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'Case ID',
                'verbose_name_plural': 'Case IDs',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ChargedWith',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('name', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_fa', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_en', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'Charged With',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DetentionStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('name', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_fa', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_en', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('detained', models.BooleanField(default=False, help_text='When this status is selected, should the prisoner be considered as currently incarcerated? This affects list view filtering.', verbose_name='Prisoner is currently in detention')),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'Detention Status',
                'verbose_name_plural': 'Detention Statuses',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DomesticLawViolated',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('name', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_fa', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_en', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'Domestic Law Violated',
                'verbose_name_plural': 'Domestic Law Violated',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='InternationalLawViolated',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('name', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_fa', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_en', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'International Law Violated',
                'verbose_name_plural': 'International Law Violated',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('name', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_fa', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_en', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'Affiliated Organization',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('forename', models.CharField(max_length=255, null=True, verbose_name='First Name', blank=True)),
                ('forename_fa', models.CharField(max_length=255, null=True, verbose_name='First Name', blank=True)),
                ('forename_en', models.CharField(max_length=255, null=True, verbose_name='First Name', blank=True)),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('surname_fa', models.CharField(max_length=255, null=True, verbose_name='Surname')),
                ('surname_en', models.CharField(max_length=255, null=True, verbose_name='Surname')),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name='Gender', choices=[(b'M', 'Male'), (b'F', 'Female')])),
                ('dob_year', models.IntegerField(null=True, verbose_name='Birth Year (Gregorian)', blank=True)),
                ('dob_month', models.IntegerField(null=True, verbose_name='Birth Month (Gregorian)', blank=True)),
                ('dob_day', models.IntegerField(null=True, verbose_name='Birth Day (Gregorian)', blank=True)),
                ('dob_year_fa', models.IntegerField(null=True, verbose_name='Birth Year (Persian)', blank=True)),
                ('dob_month_fa', models.IntegerField(null=True, verbose_name='Birth Month (Persian)', blank=True)),
                ('dob_day_fa', models.IntegerField(null=True, verbose_name='Birth Day (Persian)', blank=True)),
                ('picture', models.ImageField(upload_to=b'prisoner_pics', null=True, verbose_name='Prisoner Picture', blank=True)),
                ('needs_attention', models.BooleanField(default=False, verbose_name='Needs attention')),
                ('birth_city', models.ForeignKey(verbose_name='Birth Village/City', blank=True, to='core_types.City', null=True)),
                ('birth_province', models.ForeignKey(verbose_name='Birth Province', blank=True, to='core_types.Province', null=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('detention_status', models.ForeignKey(verbose_name='Detention Status', blank=True, to='prisoners.DetentionStatus', null=True)),
                ('ethnicity', models.ForeignKey(verbose_name='Ethnicity', blank=True, to='core_types.Ethnicity', null=True)),
                ('home_countries', models.ManyToManyField(to='core_types.Country', verbose_name='Countries Of Residence', blank=True)),
                ('religion', models.ForeignKey(verbose_name='Religion', blank=True, to='core_types.Religion', null=True)),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'Prisoner',
                'verbose_name_plural': 'Prisoners',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrisonerAffiliation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('organisation', models.ForeignKey(to='prisoners.Organisation')),
                ('prisoner', models.ForeignKey(related_name='affiliations', to='prisoners.Prisoner')),
            ],
            options={
                'verbose_name': 'Affiliation',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrisonerArrest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('arrest_year', models.IntegerField(null=True, verbose_name='Arrest Year (Gregorian)', blank=True)),
                ('arrest_month', models.IntegerField(null=True, verbose_name='Arrest Month (Gregorian)', blank=True)),
                ('arrest_day', models.IntegerField(null=True, verbose_name='Arrest Day (Gregorian)', blank=True)),
                ('arrest_year_fa', models.IntegerField(null=True, verbose_name='Arrest Year (Persian)', blank=True)),
                ('arrest_month_fa', models.IntegerField(null=True, verbose_name='Arrest Month (Persian)', blank=True)),
                ('arrest_day_fa', models.IntegerField(null=True, verbose_name='Arrest Day (Persian)', blank=True)),
                ('activity_persecuted_for', models.ForeignKey(verbose_name='Activity Persecuted For', blank=True, to='prisoners.ActivityPersecutedFor', null=True)),
                ('case_id', models.ForeignKey(verbose_name='Case ID', blank=True, to='prisoners.CaseId', null=True)),
                ('charged_with', models.ManyToManyField(to='prisoners.ChargedWith', null=True, verbose_name='Charged with', blank=True)),
                ('city', models.ForeignKey(verbose_name='City of arrest', blank=True, to='core_types.City', null=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('domestic_law_violated', models.ManyToManyField(to='prisoners.DomesticLawViolated', null=True, verbose_name='Domestic Law Violated', blank=True)),
                ('international_law_violated', models.ManyToManyField(to='prisoners.InternationalLawViolated', null=True, verbose_name='International law violated', blank=True)),
                ('prisoner', models.ForeignKey(related_name='arrests', to='prisoners.Prisoner')),
                ('province', models.ForeignKey(verbose_name='Province of arrest', blank=True, to='core_types.Province', null=True)),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('arrest_year', 'arrest_month', 'arrest_day'),
                'verbose_name': 'Arrest',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrisonerComment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('comment', models.TextField(verbose_name='Comment Text')),
                ('prisoner', models.ForeignKey(related_name='comments', to='prisoners.Prisoner')),
                ('user', models.ForeignKey(default=core_types.utils.get_request_user, verbose_name='User', to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
                'verbose_name': 'Conflicts And Considerations',
                'verbose_name_plural': 'Conflicts And Considerations',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrisonerDetention',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('social_depravation', models.TextField(null=True, verbose_name='Social Deprivation', blank=True)),
                ('arrest', models.ForeignKey(related_name='detentions', to='prisoners.PrisonerArrest')),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('prison', models.ForeignKey(verbose_name='Prison', blank=True, to='prisons.Prison', null=True)),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': 'Detention',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrisonerFile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('name', models.CharField(max_length=255, verbose_name='File Name')),
                ('name_fa', models.CharField(max_length=255, null=True, verbose_name='File Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='File Name')),
                ('description', models.TextField(null=True, verbose_name='Description', blank=True)),
                ('description_fa', models.TextField(null=True, verbose_name='Description', blank=True)),
                ('description_en', models.TextField(null=True, verbose_name='Description', blank=True)),
                ('file', models.FileField(upload_to=b'file_evidence', verbose_name='Data')),
                ('file_thumb', models.ImageField(upload_to=b'file_evidence_thumbnails', null=True, verbose_name='Thumbnail', blank=True)),
                ('file_type', models.CharField(max_length=16, choices=[(b'video', 'Video'), (b'picture', 'Picture'), (b'pdf', 'PDF')])),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('prisoner', models.ForeignKey(related_name='files', to='prisoners.Prisoner')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'File Evidence',
                'verbose_name_plural': 'File Evidence',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrisonerQuote',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('quote', models.CharField(max_length=255, verbose_name='Quote')),
                ('quote_fa', models.CharField(max_length=255, null=True, verbose_name='Quote')),
                ('quote_en', models.CharField(max_length=255, null=True, verbose_name='Quote')),
                ('source', models.CharField(max_length=255, verbose_name='Source')),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('prisoner', models.ForeignKey(related_name='quotes', to='prisoners.Prisoner')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Quote Evidence',
                'verbose_name_plural': 'Quote Evidence',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrisonerRelationship',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('forename', models.CharField(max_length=255, null=True, verbose_name='First Name', blank=True)),
                ('forename_fa', models.CharField(max_length=255, null=True, verbose_name='First Name', blank=True)),
                ('forename_en', models.CharField(max_length=255, null=True, verbose_name='First Name', blank=True)),
                ('surname', models.CharField(max_length=255, null=True, verbose_name='Surname', blank=True)),
                ('surname_fa', models.CharField(max_length=255, null=True, verbose_name='Surname', blank=True)),
                ('surname_en', models.CharField(max_length=255, null=True, verbose_name='Surname', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('prisoner', models.ForeignKey(related_name='relationships', to='prisoners.Prisoner')),
                ('related_prisoner', models.ForeignKey(related_name='+', blank=True, to='prisoners.Prisoner', null=True)),
            ],
            options={
                'verbose_name': 'Relationship',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrisonerSentence',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('death_penalty', models.BooleanField(default=False, verbose_name='Death Penalty')),
                ('fine', models.PositiveIntegerField(null=True, verbose_name='Fine (Rials)', blank=True)),
                ('number_of_lashes', models.PositiveIntegerField(null=True, verbose_name='Number Of Lashes', blank=True)),
                ('sentence_months', models.PositiveIntegerField(null=True, verbose_name='Sentence Months', blank=True)),
                ('sentence_years', models.PositiveIntegerField(null=True, verbose_name='Sentence Years', blank=True)),
                ('arrest', models.ForeignKey(related_name='sentences', to='prisoners.PrisonerArrest')),
                ('court_and_branch', models.ForeignKey(verbose_name='Court', blank=True, to='judges.CourtAndBranch', null=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('judge', models.ForeignKey(related_name='+', verbose_name='Judge', blank=True, to='judges.Judge', null=True)),
                ('sentence_type', models.ManyToManyField(to='judges.SentenceType', null=True, verbose_name='Type', blank=True)),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-sentence_type__finality', '-id'),
                'verbose_name': 'Sentence',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrisonerSource',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('link', models.URLField(null=True, verbose_name='Link', blank=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description', blank=True)),
                ('related_fields', models.CharField(default=b'', help_text='\n            Comma-separated list of field names this source relates to.\n        ', max_length=255, verbose_name='Related Fields', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('prisoner', models.ForeignKey(related_name='sources', to='prisoners.Prisoner')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrisonerTimeline',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('year', models.IntegerField(null=True, verbose_name='Year Of Event', blank=True)),
                ('month', models.IntegerField(null=True, verbose_name='Month Of Event', blank=True)),
                ('day', models.IntegerField(null=True, verbose_name='Day Of Event', blank=True)),
                ('year_fa', models.IntegerField(null=True, verbose_name='Persian Year Of Event', blank=True)),
                ('month_fa', models.IntegerField(null=True, verbose_name='Persian Month Of Event', blank=True)),
                ('day_fa', models.IntegerField(null=True, verbose_name='Persian Day Of Event', blank=True)),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('description_fa', models.TextField(max_length=255, null=True, verbose_name='Description')),
                ('description_en', models.TextField(max_length=255, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('prisoner', models.ForeignKey(related_name='timeline', to='prisoners.Prisoner')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Timeline Event',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrisonTreatment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('name', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_fa', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_en', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'Treatment In Prison',
                'verbose_name_plural': 'Treatment In Prison',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('name', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_fa', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('name_en', models.CharField(max_length=255, unique=True, null=True, verbose_name='Name', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'Relationship Type',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SentenceBehaviour',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_published', models.BooleanField(default=False, db_index=True, verbose_name='Approved for publishing?')),
                ('description', models.TextField(null=True, verbose_name='Description of Behaviour', blank=True)),
                ('description_fa', models.TextField(null=True, verbose_name='Description of Behaviour', blank=True)),
                ('description_en', models.TextField(null=True, verbose_name='Description of Behaviour', blank=True)),
                ('behaviour_type', models.ForeignKey(related_name='+', verbose_name='Type', to='judges.BehaviourType')),
                ('created_by', models.ForeignKey(related_name='+', default=core_types.utils.get_request_user, blank=True, to=settings.AUTH_USER_MODEL, null=True, verbose_name='Created By')),
                ('sentence', models.ForeignKey(related_name='behaviours', to='prisoners.PrisonerSentence')),
                ('updated_by', models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'Sentence Judicial Behaviour',
            },
            bases=(models.Model,),
        ),
        migrations.AlterUniqueTogether(
            name='prisonersource',
            unique_together=set([('prisoner', 'name')]),
        ),
        migrations.AddField(
            model_name='prisonerrelationship',
            name='relationship_type',
            field=models.ForeignKey(verbose_name='Type', to='prisoners.RelationshipType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='prisonerrelationship',
            name='updated_by',
            field=models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='prisonerdetention',
            name='treatment',
            field=models.ManyToManyField(to='prisoners.PrisonTreatment', null=True, verbose_name='Treatment in prison', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='prisonerdetention',
            name='updated_by',
            field=models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='prisoneraffiliation',
            name='relationship_type',
            field=models.ForeignKey(to='prisoners.RelationshipType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='prisoneraffiliation',
            name='updated_by',
            field=models.ForeignKey(related_name='+', verbose_name='Last Updated By', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
    ]
