# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-24 19:38
from __future__ import unicode_literals

import core_types.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners', '0026_prisonerarrest_partial_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='explanation_en',
            field=models.TextField(blank=True, null=True, verbose_name='Any extra explanation needed to be added to this prisoner'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='explanation_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Any extra explanation needed to be added to this prisoner'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='latest_secondary_activity_name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Most recent secondary activity (cached for search results)'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='latest_secondary_activity_name_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Most recent secondary activity (cached for search results)'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='latest_tertiary_activity_name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Most recent tertiary activity (cached for search results)'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='latest_tertiary_activity_name_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Most recent tertiary activity (cached for search results)'),
        ),
        migrations.AddField(
            model_name='prisonerarrest',
            name='secondary_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_activity', to='prisoners.ActivityPersecutedFor', verbose_name='Secondary Activity'),
        ),
        migrations.AddField(
            model_name='prisonerarrest',
            name='tertiary_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_activity', to='prisoners.ActivityPersecutedFor', verbose_name='Tertiary Activity'),
        ),
        migrations.AddField(
            model_name='prisonertimeline',
            name='source_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Source Link'),
        ),
        migrations.AlterField(
            model_name='detentionstatus',
            name='detained',
            field=models.BooleanField(default=True, help_text='When this status is selected, should the prisoner be considered as currently incarcerated? This affects list view filtering.', verbose_name='Prisoner is currently in detention'),
        ),
        migrations.AlterField(
            model_name='prisonerarrest',
            name='charged_with',
            field=models.ManyToManyField(blank=True, to='prisoners.ChargedWith', verbose_name='Charged with'),
        ),
        migrations.AlterField(
            model_name='prisonerarrest',
            name='domestic_law_violated',
            field=models.ManyToManyField(blank=True, to='prisoners.DomesticLawViolated', verbose_name='Domestic Law Violated'),
        ),
        migrations.AlterField(
            model_name='prisonerarrest',
            name='international_law_violated',
            field=models.ManyToManyField(blank=True, to='prisoners.InternationalLawViolated', verbose_name='International law violated'),
        ),
        migrations.AlterField(
            model_name='prisonerarrest',
            name='partial_date',
            field=core_types.fields.PartialDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prisonerdetention',
            name='prison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detentions', to='prisons.Prison', verbose_name='Prison'),
        ),
        migrations.AlterField(
            model_name='prisonerdetention',
            name='treatment',
            field=models.ManyToManyField(blank=True, to='prisoners.PrisonTreatment', verbose_name='Treatment in prison'),
        ),
        migrations.AlterField(
            model_name='prisonersentence',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='judges.Judge', verbose_name='Judge'),
        ),
        migrations.AlterField(
            model_name='prisonersentence',
            name='sentence_type',
            field=models.ManyToManyField(blank=True, to='judges.SentenceType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='prisonertimeline',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='prisonertimeline',
            name='description_en',
            field=models.TextField(max_length=1024, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='prisonertimeline',
            name='description_fa',
            field=models.TextField(max_length=1024, null=True, verbose_name='Description'),
        ),
    ]
