# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-01 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners', '0027_auto_20190924_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisonertimeline',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='prisonertimeline',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='prisonertimeline',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
